# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Deployment unique inputs
kubernetes-deployment-env-sub-path:
  description: 'Path to deployment environment variables directory'
  required: false
  type: string
  default: 'src/deployment-env'
kubernetes-deployment-additional-labels:
  description: 'Additional labels for Deployment resources (key=value,key=value)'
  required: false
  type: string
  default: ''
kubernetes-deployment-additional-annotations:
  description: 'Additional annotations for Deployment resources (key=value,key=value)'
  required: false
  type: string
  default: ''
kubernetes-deployment-max-surge:
  description: 'Max surge during rolling update (integer or percentage, e.g., 1 or 25%)'
  required: false
  type: string
  default: '1'
kubernetes-deployment-max-unavailable:
  description: 'Max unavailable during rolling update (integer or percentage, e.g., 0 or 25%)'
  required: false
  type: string
  default: '0'
