name: Basic Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/basic-quality-and-versioning.yaml
    with:
      block-conventional-commits: true
      block-slash-containing-branches: true
      pre-tagging-tests-script-sub-path: bin/pre-tagging.bash
    permissions:
      actions: read
      contents: write
      checks: write
