name: Basic Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/basic-quality-and-versioning.yaml
    with:
      block-conventional-commits: true
      block-slash-containing-branches: true
      hook-pre-tagging-tests-script-sub-path: bin/pre-tagging.bash
      github-release-substituted-files: .github/token-substitution-and-gh-release-test.yaml
    permissions:
      contents: write
      checks: write
